[package]
name = "aquila"
version = "0.1.1"
authors = ["Avi Srivastava <avi.srivastava@nyu.edu>"]

[lib]
crate-type = ["staticlib"]

[dependencies.indus]
git = "https://github.com/parazodiac/Indus"
branch = "main"
version = "0.1.1"
