# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Oxidized_MoransI <- function(weight_folder_path, values_folder_path, out_file_path) {
    .Call('_aquila_Oxidized_MoransI', PACKAGE = 'aquila', weight_folder_path, values_folder_path, out_file_path)
}

Oxidized_GearyC <- function(weight_folder_path, values_folder_path, out_file_path) {
    .Call('_aquila_Oxidized_GearyC', PACKAGE = 'aquila', weight_folder_path, values_folder_path, out_file_path)
}

