# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsGamma <- function() {
    invisible(.Call('_Circus_gibbsGamma', PACKAGE = 'Circus'))
}

correlationMatrix <- function(atac, rna) {
    .Call('_Circus_correlationMatrix', PACKAGE = 'Circus', atac, rna)
}

